# Generated by Django 3.2.5 on 2021-07-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sensing', '0002_auto_20210701_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temparature', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sensing.table1')),
            ],
        ),
    ]
