# Generated by Django 3.2.5 on 2021-07-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table1',
            name='id',
        ),
        migrations.AddField(
            model_name='table1',
            name='reference_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
