# Generated by Django 3.2.5 on 2021-07-07 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sensing', '0003_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='dat',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='data',
            name='tim',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
